### ISSUE TITLE
"--iface=auto" is hard-code in socketplane.sh

### ISSUE THREAD

**Issue by LipingMao** [socketplane/socketplane#86] opened 2015-01-05 15:17 UTC
I try to use socketplane in my openstack VMs. And I find that if I use "--iface=auto", the consul cluster can't work well. After I modify "--iface=eth0" in socketplane.sh, it works in my envorinment(My Openstack VMs have only one interface eth0). So I think it will be better if "--iface" is configurable in socketplane command .

**Comment by mavenugo** [comment] 2015-01-05 15:28
thanks @LipingMao . Agreed.

We have #57 opened already for this. Also, there is another enhancement #69 which handles the static provisioning use-case with an option to listen on a particular interface.

If you agree, we should close this as a duplicate of #57 
Please add any comments / suggestions / pull PR against #57 and #69 . Thanks.

**Comment by LipingMao** [comment] 2015-01-05 15:33
Thanks @mavenugo for the info, I totally agree this  should be closed.  #57 LGTM  :-)

**Comment by mavenugo** [comment] 2015-01-05 15:34
Closing the issue as this is a duplicate of #57

**Closed by mavenugo** 2015-01-05 15:34 UTC
